feat(01-building-blocks): added  failing part 01-building-blocks.yaml

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,3 +6,12 @@ jobs:
     steps:
       - name: Say hello
         run: echo "Hello world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
